
const gttActiveLanguages = [
    {code:'af', lang : 'Afrikaans'},
    {code:'sq', lang : 'Albanian'},
    {code:'ar', lang : 'Arabic'},
    {code:'hy', lang : 'Armenian'},
    {code:'ca', lang : 'Catalan'},
    {code:'zh', lang : 'Chinese'},
    {code:'zh-cn', lang : 'Chinese (Mandarin/China)'},
    {code:'zh-tw', lang : 'Chinese (Mandarin/Taiwan)'},
    {code:'zh-yue', lang : 'Chinese (Cantonese)'},
    {code:'hr', lang : 'Croatian'},
    {code:'cs', lang : 'Czech'},
    {code:'da', lang : 'Danish'},
    {code:'nl', lang : 'Dutch'},
    {code:'en', lang : 'English'},
    {code:'en-au',lang : 'English (Australia)'},
    {code:'en-uk',lang : 'English (United Kingdom)'},
    {code:'en-us',lang : 'English (United States)'},
    {code:'eo',lang : 'Esperanto'},
    {code:'fi',lang : 'Finnish'},
    {code:'fr',lang : 'French'},
    {code:'de',lang : 'German'},
    {code:'el',lang : 'Greek'},
    {code:'ht',lang : 'Haitian Creole'},
    {code:'hi',lang : 'Hindi'},
    {code:'hu',lang : 'Hungarian'},
    {code:'is',lang : 'Icelandic'},
    {code:'id',lang : 'Indonesian'},
    {code:'it',lang : 'Italian'},
    {code:'ja',lang : 'Japanese'},
    {code:'ko',lang : 'Korean'},
    {code:'la',lang : 'Latin'},
    {code:'lv',lang : 'Latvian'},
    {code:'mk',lang : 'Macedonian'},
    {code:'no',lang : 'Norwegian'},
    {code:'pl',lang : 'Polish'},
    {code:'pt',lang : 'Portuguese'},
    {code:'pt-br',lang : 'Portuguese (Brazil)'},
    {code:'ro',lang : 'Romanian'},
    {code:'ru',lang : 'Russian'},
    {code:'sr',lang : 'Serbian'},
    {code:'sk',lang : 'Slovak'},
    {code:'es',lang : 'Spanish'},
    {code:'es-es',lang : 'Spanish (Spain)'},
    {code:'es-us',lang : 'Spanish (United States)'},
    {code:'sw',lang : 'Swahili'},
    {code:'sv',lang : 'Swedish'},
    {code:'ta',lang : 'Tamil'},
    {code:'th',lang : 'Thai'},
    {code:'tr',lang : 'Turkish'},
    {code:'vi',lang : 'Vietnamese'},
    {code:'cy',lang : 'Welsh'}
]


module.exports = {
    gttActiveLanguages
}

